### ISSUE TITLE
RoomDetailsPanel & ScheduleSlot sometimes show no organizer name

### ISSUE THREAD

**Issue by nick-bratton** [ixds/room-status#13]
In the method currentOrganizer() on the ScheduleFar class, for example, there's a condition `this.currentEntry.organizer.emailAddress.name === attendee` that is not true when this happens. I see that in one case, the `attendee` is Tobias Gerber but `this.currentEntry.organizer` is an object with its .address key set to "room-ber-woz@ixds.com" and it's .name key set t "Room–BER–Woz"

**Comment by jperals** [comment]
Oops, it looks like I have a couple of unpushed commits:

```
* 73f1623 (HEAD -> master) Only show organizer's name, not the other attendees'
* bf48dbe Convert calendar entry times from UTC to local times
```

As you can see, one seems to have to do with this and the other one fixes the one-hour-off issue that we were talking about earlier.

Unfortunately I am getting a conflict when pulling because you seem to have switched from spaces to tabs (is your editor not using the .editorconfig file or is the .editorconfig file not specific enough?). I think I'll push to develop and then you merge, what do you think? (Also, this way I won't be unnecessarily triggering the automated deployment system)

**Comment by jperals** [comment]
I just pushed those two commits to a new `develop` branch.

**Comment by nick-bratton** [comment]
I'm taking care of the merge now. I'll implement the fix you made in ScheduleSlot also in the RoomDetailsPanel and then push to master.

Thanks for the quick reply Joan :)

**Comment by nick-bratton** [comment]
I think commit 73f1623 fixes the issue either not entirely or there's another issue with the same symptom....

Sometimes there are entries with an empty attendees array. One case I've seen is that an entry's organizer .address and .name props are `room-muc-loggia@ixds.com` and `Room-MUC-Loggia`. The entry does have a .name prop in this case: 'Impact Circle'. See the screenshot:

<img width="1298" alt="Screenshot 2019-03-18 at 14 04 35" src="https://user-images.githubusercontent.com/47389141/54535639-3e8ba180-498f-11e9-9d3a-9e94cdca1b38.png">

**Comment by nick-bratton** [comment]
Made a fix in the ScheduleSlot to grab this.entry.name if there are no attendees to prevent the blank space in the organizer field
